version: "3.0"
services:
  elasticsearch:
    container_name: elastic-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    environment:
      - cluster.name=elastic-cluster
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - ek-net
    ports:
      - 9200:9200
  kibana:
    container_name: kibana-container
    image: docker.elastic.co/kibana/kibana:8.8.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic-container:9200
      
    networks:
      - ek-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
networks:
  ek-net:
    driver: bridge
volumes:
    esdata:
